updated getcluster message
kubesimplify/ksctl pull request #63
Opened 2023-01-21 15:31 UTC by bishal7679

Signed-off-by: bishal7679 <bishalhnj127@gmail.com>

Description:
Updated get-clusters command when its null

2023-01-21 15:31 UTC, bishal7679 commented
Its small changes!
@dipankardas011 PHAL!

2023-01-22 05:20 UTC, dipankardas011 commented
@AvineshTripathi or @kranurag7 you can review this PR

2023-01-22 05:21 UTC, dipankardas011 commented
Will not be able to contribute for 1 or 3 days here
sorry for the inconvience

2023-02-18 12:07 UTC, dipankardas011 commented
@bishal7679 whats your progress

2023-03-04 09:48 UTC, dipankardas011 commented
@bishal7679 are their any progress?

2023-03-04 12:52 UTC, bishal7679 commented
@dipankardas011 I got disconnected for my exam sorry for the long waiting response. In this pr only fmt message has been changed. Do u want any further changes??

2023-03-08 05:36 UTC, karnatisrinivas reviewed
Cosmetic changes, LGTM

2023-03-08 15:55 UTC, dipankardas011 requested changes
Do check the comments

2023-03-08 15:55 UTC, dipankardas011 commented on cli/cmd/getCluster.go
> +	}
when the json.marshal converts a empty json it returns nil does that compares to len() == 0 ?

2023-03-09 03:40 UTC, dipankardas011 commented on cli/cmd/getCluster.go
> +	}
@bishal7679 you should check for nil as its of type []byte

2023-03-19 11:21 UTC, dipankardas011 requested changes
Require changes

2023-03-19 11:21 UTC, dipankardas011 commented on cli/cmd/getCluster.go
> +	}
@bishal7679 have you tested this in local system?

2023-03-19 14:19 UTC, bishal7679 commented
@dipankardas011 Here it is working!
![Mar-03-19-47](https://user-images.githubusercontent.com/70086051/226182220-b7f1c549-3c2f-4b35-b1d3-47ddbe8e1482.png)

2023-03-19 17:29 UTC, dipankardas011 commented
got it

2023-03-19 17:29 UTC, dipankardas011 approved these changes
LGTM

2023-03-19 17:31 UTC, dipankardas011 commented
also @bishal7679 can you use the log.Err(""No cluster)

2023-03-19 17:32 UTC, dipankardas011 commented
> also @bishal7679 can you use the
> 
> ```go
> log.Err("No cluster")
> ```

use the logger package

2023-03-19 17:33 UTC, dipankardas011 commented
or else decide whether its a error or just a notice or Success message what are your opinion @AvineshTripathi

2023-03-19 17:36 UTC, bishal7679 commented
> or else decide whether its a error or just a notice or Success message what are your opinion @AvineshTripathi

it would be perfect I think!

2023-03-19 18:23 UTC, AvineshTripathi commented
I think notice or successs should be better and not error

2023-03-29 06:53 UTC, dipankardas011 commented
@bishal7679 you can fix that I will merge the PR today 😄

2023-04-21 15:14 UTC, closed without merging