AWS cred
kubesimplify/ksctl pull request #92
Opened 2023-05-02 02:40 UTC by riteshsonawane1372

# Tasks / Issue :construction: 🔧 

- [ ] Task / issue no #17 
- [ ] other task items

# Solution :heavy_check_mark:

# Screenshots :framed_picture:

# Note to reviewers :notebook:

2023-05-02 05:50 UTC, dipankardas011 commented
I think this dev branch is not having the expected commits may be fault by my side

2023-05-02 05:55 UTC, dipankardas011 commented
@riteshsonawane1372 fixed the dev branch may be you need to rebase you commits

2023-05-03 01:59 UTC, riteshsonawane1372 commented
> @riteshsonawane1372 fixed the dev branch may be you need to rebase you commits

![image](https://user-images.githubusercontent.com/72307121/235820100-f645120f-0803-49df-a144-7363560e1f9e.png)

2023-05-03 16:56 UTC, dipankardas011 requested changes

2023-05-03 16:56 UTC, dipankardas011 commented on api/aws/main.go
> +		panic(err.Error())
you can put here logger.Err and return false

2023-05-03 16:56 UTC, dipankardas011 commented on api/aws/main.go
> +		panic(err.Error())
same here as well

2023-05-06 01:18 UTC, dipankardas011 approved these changes

2023-05-07 07:29 UTC, dipankardas011 commented
@riteshsonawane1372 do fill the solution part of this PR description so that we can merge

2023-05-07 07:36 UTC, dipankardas011 commented
@riteshsonawane1372 also if you can do rebase with latest dev branch

2023-05-08 03:07 UTC, riteshsonawane1372 commented
> @riteshsonawane1372 also if you can do rebase with latest dev branch

I wasn't able to rebase the branch, and I would greatly appreciate any assistance you can provide.

2023-05-08 05:13 UTC, dipankardas011 approved these changes

2023-05-08 05:14 UTC, dipankardas011 commented
@AvineshTripathi it's wierd that automerge not working here

2023-05-09 06:50 UTC, dipankardas011 commented
@riteshsonawane1372 thanks for creating this pr 🙏

2023-05-09 10:17 UTC, AvineshTripathi commented
> @AvineshTripathi it's wierd that automerge not working here

we should debug!

2023-05-10 09:58 UTC, riteshsonawane1372 commented
> @riteshsonawane1372 thanks for creating this pr 🙏

 If possible, create a new branch "dev-aws" from main

2023-05-13 16:04 UTC, merged